### ISSUE TITLE
plotting overloads GPU with large data sets 

### ISSUE THREAD

**Issue by DavidTingley** [FeeLab/seqNMF#2]
Hi Emily and Andrew,

I wanted to start by thanking you for creating such a useful tool, I have been very happy with some of the preliminary results from this algorithm.  I'm excited to dive in further!

One thing I have noticed is that with fairly large data sets (~150 neurons and >100000 samples) the plotting functionality seems to overload GPU memory and leads to a segmentation fault in Matlab.  I am not positive, but I believe the issue comes from lines 95-100 of SimpleWHPlot.m.

My current solution has been to turn plotting off until the algorithm has finished.  Alternatively, I think plotting the factor timecourses as a heatmap may help to decrease GPU demand.

Thanks again!  Best,
David Tingley
Buzsaki Lab

**Comment by emackev** [comment]
Hi David, 

Thanks for letting us know about this! And happy preliminary results are looking nice!!

Turning plotting off while you're running the algorithm is a good idea -- it'll run faster. 

I think you're right that patches are slowest/most memory intensive part of the plotting.  I've had plotting take a while for WHPlot, because there are a lot of patches (each neuron is a patch), but I haven't had that in SimpleWHPlot (only the factors are patches).  Maybe you are using a larger number of factors than I usually use?  In general, if Matlab's running out of memory it's likely trying to plot more things than your screen has pixels to show, so it's worth asking it to plot fewer things.  If you are running many factors, you could plot a subset of the factors.  You could also plot a subset of the timebins (plotAll = 0 in the input to SimpleWHPlot will plot the data at the same timescale as the factors, or you could manually choose a different time window). 

Best,
Emily M.

**Comment by DavidTingley** [comment]
thanks for the response on this!
