### ISSUE TITLE
How to optimize L

### ISSUE THREAD

**Issue by etterguillaume** [FeeLab/seqNMF#3]
Hi and thanks so much for making this tool open source, this is really helpful!
While I understand how to find the most appropriate K/lambda (the demo is pretty explicit), I am wondering if there would be a way to optimize L (find the exact sequence length). Right now, in cases with prominent and reliable sequences, I can vary L and the reconstruction will still work fine (every occurence is found, cell order is consistent) however H will not necessarily point to the actual beginning of the sequence (and in some cases give the false impression that the sequence starts earlier). Would you recommend any specific method to determine the best appropriate L (that is, without any prior over the type of behaviour being performed and/or neural activity)? Perhaps iteratively, just like for K/lambda?

Thanks a lot and take care!
Guillaume

**Comment by emackev** [comment]
Hi Guillaume! Since different sequences in the dataset might be different lengths, I wouldn't suggest optimizing L across the entire dataset.  One thing I've done to get a sense of the length and start time of a sequence is look at the cross correlation between each neuron's timecourse and the H.  Define participating neurons as neurons with a significant peak in the cross correlation (compared to circularly shifted data).  Then, you can see where the first and last participating neurons tend to fire relative to the H's by looking for what time lag has high peak cross correlation.  Hope this helps, let me know if you have questions! Also, sorry for the delay responding... I didn't have notifications set up properly and only just saw this.
