### ISSUE TITLE
Spectrogram Examples Missing Data?

### ISSUE THREAD

**Issue by J-Fo-S** [FeeLab/seqNMF#4]
Hello - lovely code, thank you for the release. One small issue I've encountered is that the package seems not to include the singinginfo.mat and the data from '\\feevault\data0\AcqGui\TotsSomeDataFromCrcns\ required to produce the spectrogram experiments (the songs, not the neural data). Thus I cannot run the SpectrogramExample.m in the misc_elm folder. How may I obtain the data? Thank you and apologies if I missed something obvious.

Missing are these: 
pathname = '\\feevault\data0\AcqGui\TotsSomeDataFromCrcns';
datafolder = fullfile(pathname, 'to3567\2013-03-19\HVCp-1'); 
analysisfile =  fullfile(pathname, 'Analysis_files\HVCp\to3567_2013-03-19_HVCp-1');
SoundFiles = dir(fullfile(datafolder, '*chan0.mat'));

**Comment by emackev** [comment]
Hi, thanks for catching this, and for using seqNMF! I probably should not have included the SpectrogramExample.m file in the posted code, because it is a script that refers to local paths on the computer I was using in Fee Lab, in many places, both to load things, and also to save things.  What I would suggest, if you're interested in using seqNMF on spectrograms, is to start from the demo.m script, and use a spectrogram as your input. That's what the SpectrogramExample is doing.  Spectrograms should work similarly to other types of input, though you may want to run more iterations (in the example I did 1000, where 100 was usually plenty for sparser data like the neural data I recorded). As with any dataset, it also makes sense to think about what L and K make sense (in the example, I chose L to be slightly longer than a typical zebra finch syllable, and K to be slightly more than the number of syllables a zebra finch has).  If you're interested in the specific example referred to in SpectrogramExample.m, it is in this public repository: https://crcns.org/data-sets/aa/am-3. A good resource for computing spectrograms from raw audio files, including good zebra finch examples, is: http://soundanalysispro.com/matlab-sat.  Thanks again for using seqNMF, and please reach out if you have more questions!

**Comment by J-Fo-S** [comment]
Thank you for the quick and helpful reply. The data and paths are easy to solve, but I am finding the demo a lot to unpack. It seems now that SpectrogramExample.m is just missing one linked function:     [S,Time,F] = spectrogramELM(A.sound,A.fs, .005, 1,[500 8000]); 

Would it be possible to share a gist of this? Seems a much cleaner way to experiment with spectrograms than with all the neural data overlap contained in the demo. If not though, thanks anyways for the help.
